service:
  name: aws-user-util

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "iam:GetLoginProfile"
       Resource: "arn:aws:iam::656901843610:user/*"  

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
